import { Foods } from "./schema";

export const drink: Foods[] = [
  {
    id: 31,
    name: "Float Cha",
    price: 15000,
    description: "Ini bla bla bla blubub blubuu",
    image: "/img/mn1.png",
    category: "drink",
  },
  {
    id: 32,
    name: "Lemon",
    price: 15000,
    description: "Ini bla bla bla blubub blubuu",
    image: "/img/mn2.png",
    category: "drink",
  },
  {
    id: 33,
    name: "Coconut Brrr",
    price: 15000,
    description: "Ini bla bla bla blubub blubuu",
    image: "/img/mn3.png",
    category: "drink",
  },
  {
    id: 34,
    name: "Soft Water",
    price: 15000,
    description: "Ini bla bla bla blubub blubuu",
    image: "/img/mn4.png",
    category: "drink",
  },
  {
    id: 35,
    name: "Float Choco",
    price: 15000,
    description: "Ini bla bla bla blubub blubuu",
    image: "/img/mn5.png",
    category: "drink",
  },
  {
    id: 36,
    name: "Tea Plas Straw",
    price: 15000,
    description: "Ini bla bla bla blubub blubuu",
    image: "/img/mn6.png",
    category: "drink",
  },
  {
    id: 37,
    name: "Mix Fruits",
    price: 15000,
    description: "Ini bla bla bla blubub blubuu",
    image: "/img/mn7.png",
    category: "drink",
  },
  {
    id: 38,
    name: "Coconut Sans",
    price: 15000,
    description: "Ini bla bla bla blubub blubuu",
    image: "/img/mn8.png",
    category: "drink",
  },
  {
    id: 39,
    name: "Soda Happy",
    price: 15000,
    description: "Ini bla bla bla blubub blubuu",
    image: "/img/mn9.png",
    category: "drink",
  },
  {
    id: 310,
    name: "Lemongrase brrr",
    price: 15000,
    description: "Ini bla bla bla blubub blubuu",
    image: "/img/mn10.png",
    category: "drink",
  },
  {
    id: 311,
    name: "Pink Sweet",
    price: 15000,
    description: "Ini bla bla bla blubub blubuu",
    image: "/img/mn11.png",
    category: "drink",
  },
  {
    id: 312,
    name: "Water Pink",
    price: 15000,
    description: "Ini bla bla bla blubub blubuu",
    image: "/img/mn12.png",
    category: "drink",
  },
];
